// @ts-check

import apiSidebar from './docs/api/sidebar.ts';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  apiSidebar,
};

export default sidebars;
